[global]
# Shared patch file path (optional). If missing, auto-fetch rules apply.
patches = "./patches/youtube.mpp"


[morphe-cli]
patches_repo = "MorpheApp/morphe-cli"
# lock morphe-cli jar by original release filename (optional)
# if this file already exists in ./morphe-cli, download will be skipped
# ver = "morphe-cli-1.6.3-all.jar"


[patches]
patches_repo = "MorpheApp/morphe-patches"
# mode: stable | dev
# stable: name does not include "dev"
# dev: name includes "dev"
mode = "stable" 
# lock patch bundle by original release filename (optional)
# if this file already exists in ./patches, download will be skipped
# ver = "patches-1.23.0-dev.1.mpp"



[youtube]
# apk mode:
# - local: use local_apk/source-apk directly
# - remote: remote fallback order = apkmirror -> archive
# - empty/invalid/other value: skip this app section
# remote base URLs are read from scripts/download-apk/url.json
apk = "local"

# package_name = "com.google.android.youtube"
# local_apk = "./source-apk/youtube.apk"
