[morphe-cli]
mode = "stable"
patches_repo = "MorpheApp/morphe-cli"
repo_options = ["MorpheApp/morphe-cli"]

[patches]
mode = "stable"
patches_repo = "MorpheApp/morphe-patches"
repo_options = ["MorpheApp/morphe-patches"]

[youtube]
mode = false
package_name = "com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://dn790002.ca.archive.org/0/items/jhc-apks/apks/com.google.android.youtube/"

[youtube_music]
mode = false
package_name = "com.google.android.apps.youtube.music"
patches_mode = "custom"
patches = ["Hide music video ads", "Permanent repeat", "Custom branding", "Change header", "Hide buttons", "Hide category bar", "Change miniplayer color", "Enable forced miniplayer", "Miniplayer previous and next buttons", "Navigation bar", "Hide 'Get Music Premium'", "Change start page", "Theme", "Bypass certificate checks", "Disable DRC audio", "Enable exclusive audio playback", "Force original audio", "Remove background playback restrictions", "Enable debugging", "Check watch history domain name resolution", "GmsCore support", "Sanitize sharing links", "Disable QUIC protocol"]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://dn790002.ca.archive.org/0/items/jhc-apks/apks/com.google.android.apps.youtube.music/"

[reddit]
mode = false
package_name = "com.reddit.frontpage"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://dn790002.ca.archive.org/0/items/jhc-apks/apks/com.reddit.frontpage/"
